export const names = [
  'Hendra Liu',
  'Melisa',
  'Joseph',
  'Nathaniel',
  'Hilda',
  'Alex Wu',
  'Bambang',
  'Clarine',
  'Juan',
  'Jennifer',
  'Ling',
  'Michael Geraldo',
  'Laura',
  'Christian Jason',
  'Jonathan',
  'Putri',
  'Willy',
  'Jhonny',
  'Matthew',
  'Erick',
  'Eunike',
  'Jessica',
  'Gentrix',
  'Helpi',
  'Andreas',
  'Michelle',
  'Gerard',
  'Maylia',
  'Cristianto',
  'Kezia',
  'Phebee',
  'Haidee',
  'Chandra',
  'Valerie',
  'Julio',
  'Daniel',
  'Anton Gunarto',
  'James Minandar',
  'Nita',
  'Yendy',
  'Haryanto',
  'Juli',
  'Ronald',
  'Ishak',
  'Liman',
  'Ema',
  'Teddy',
  'Wenny Handoko',
  'Lenny',
  'Merry',
  'July',
  'Diana',
  'Tan Giok Eng',
  'Hartono',
  'Krestian',
  'Wiwin',
  'Ayen',
  'Hasan',
  'Lanny',
  'Aimee',
  'Martha',
  'Sharen',
  'Rachel',
  'Rahel',
  'Julio Fandy',
  'Gunaryo'
]

export const randomName = () => `Contoh: ${names[Math.floor(Math.random() * names.length)]}`

export const absenTitles = [
  'Acara Kebersamaan Penatalayan 2022',
  'Ibadah Umum 1',
  'Ibadah Pemuda & Remaja',
  'Ibadah Sekolah Minggu',
  'Ibadah Natal 2022'
]

export const randomAbsenTitle = () => `Contoh: ${absenTitles[Math.floor(Math.random() * absenTitles.length)]}`
